version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...
    - go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest

builds:
  - id: gwtm
    main: ./cmd/git-worktree-manager
    binary: gwtm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      pre:
        - cmd: go run ./cmd/git-worktree-manager/gen_versioninfo.go {{ .Version }}
        - cmd: goversioninfo -64 -o cmd/git-worktree-manager/resource_windows_amd64.syso cmd/git-worktree-manager/versioninfo.json
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: [binary]
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
