# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  BINARY: gwtm
  VERSION:
    sh: git describe --exact-match --tags 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  DATE:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "unknown"
  LDFLAGS: -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.DATE}}

tasks:
  build:
    desc: Build the binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY}} ./cmd/git-worktree-manager

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  install:
    desc: Install binary to GOPATH/bin or HOME/.git-worktree-manager
    deps: [build]
    cmds:
      - |
        if [ -n "$GOPATH" ]; then
          cp {{.BINARY}} "$GOPATH/bin/"
        else
          mkdir -p "$HOME/.git-worktree-manager"
          cp {{.BINARY}} "$HOME/.git-worktree-manager/"
        fi

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY}} {{.BINARY}}.exe
      - go clean

  fmt:
    desc: Format the code
    cmds:
      - gofmt -s -w .

  lint:
    desc: Run linter if installed
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        else
          echo "golangci-lint not installed, skipping"
        fi
